name: container

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'gh-pages'
  schedule:
    - cron: '38 3 */7 * *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-deploy]

concurrency:
  group: ${{ github.workflow }}-{{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  container-build:
    permissions:
      contents: read
      packages: write
    uses: openstreetmap/github-shared-workflows/.github/workflows/container-build-publish.yml@main
