name: test-pr
on:
 pull_request:
    types: [opened, reopened]
permissions:
  contents: read
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build --clean -s
